version: "3"

services:
  api-dev:
    image: slapjd/musicstreamer-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
#     - HOST:CONTAINER
    volumes:
      - ./api:/usr/src/app
      - ./database:/var/lib/mysql
      - ${MUSIC_FOLDER}:${VIRTUAL_MUSIC_FOLDER}
      - ${NGINX_FOLDER}:${VIRTUAL_NGINX_FOLDER}:rw
    env_file:
      - .env
    restart: unless-stopped
  mariadb:
    image: mariadb
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
    restart: unless-stopped